from fastapi import APIRouter

from app.api.v1.endpoints import (
    adapters,
    annotation_classes,
    annotation_schemas,
    annotation_sets,
    annotations,
    auth,
    automation,
    basemaps,
    datasets,
    events,
    feature_layers,
    health,
    jobs,
    map_layers,
    maps,
    models,
    organization_members,
    organizations,
    projects,
    styles,
    stac,
    storage_download,
    tile_sources,
    tiles,
    users,
    webhooks,
)

api_router = APIRouter()
api_router.include_router(health.router)
api_router.include_router(auth.router)
api_router.include_router(webhooks.router)
api_router.include_router(organizations.router)
api_router.include_router(users.router)
api_router.include_router(organization_members.router)
api_router.include_router(projects.router)
api_router.include_router(maps.router)
api_router.include_router(map_layers.router)
api_router.include_router(datasets.router)
api_router.include_router(models.router)
api_router.include_router(jobs.router)
api_router.include_router(adapters.router)
api_router.include_router(stac.router)
api_router.include_router(tiles.router)
api_router.include_router(styles.router)
api_router.include_router(annotation_schemas.router)
api_router.include_router(annotation_classes.schema_router)
api_router.include_router(annotation_classes.router)
api_router.include_router(annotation_sets.router)
api_router.include_router(annotation_sets.set_router)
api_router.include_router(annotation_sets.project_router)
api_router.include_router(annotation_sets.map_router)
api_router.include_router(annotations.router)
api_router.include_router(annotations.map_router)
api_router.include_router(basemaps.router)
api_router.include_router(tile_sources.router)
api_router.include_router(feature_layers.router)
api_router.include_router(automation.router)
api_router.include_router(storage_download.router)
api_router.include_router(events.router)
