"""Add annotation set link to map layer.

Revision ID: 9165194191ce
Revises: 2d3e4f5a6b7c
Create Date: 2026-03-19 18:16:35.484825
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

revision = "9165194191ce"
down_revision = "2d3e4f5a6b7c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_layers', sa.Column('annotation_set_id', UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(
        'idx_map_layers_annotation_set',
        'map_layers', 'annotation_sets',
        ['annotation_set_id'], ['id'],
        ondelete='CASCADE'
    )
    # Drop old check constraint
    op.drop_constraint('ck_map_layers_source', 'map_layers', type_='check')
    # Create new check constraint with annotation_set condition
    op.create_check_constraint(
        'ck_map_layers_source',
        'map_layers',
        """
        (source_type = 'dataset' AND dataset_id IS NOT NULL AND stac_item_id IS NULL AND tile_service_url IS NULL AND annotation_set_id IS NULL) OR
        (source_type = 'stac_item' AND stac_item_id IS NOT NULL AND dataset_id IS NULL AND tile_service_url IS NULL AND annotation_set_id IS NULL) OR
        (source_type = 'tile_service' AND tile_service_url IS NOT NULL AND dataset_id IS NULL AND stac_item_id IS NULL AND annotation_set_id IS NULL) OR
        (source_type = 'annotation_set' AND annotation_set_id IS NOT NULL AND dataset_id IS NULL AND stac_item_id IS NULL AND tile_service_url IS NULL)
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the new check constraint
    op.drop_constraint('ck_map_layers_source', 'map_layers', type_='check')
    # Recreate the old check constraint
    op.create_check_constraint(
        'ck_map_layers_source',
        'map_layers',
        """
        (source_type = 'dataset' AND dataset_id IS NOT NULL AND stac_item_id IS NULL AND tile_service_url IS NULL) OR
        (source_type = 'stac_item' AND stac_item_id IS NOT NULL AND dataset_id IS NULL AND tile_service_url IS NULL) OR
        (source_type = 'tile_service' AND tile_service_url IS NOT NULL AND dataset_id IS NULL AND stac_item_id IS NULL)
        """
    )
    # Drop foreign key and column
    op.drop_constraint('idx_map_layers_annotation_set', 'map_layers', type_='foreignkey')
    op.drop_column('map_layers', 'annotation_set_id')
    # ### end Alembic commands ###