"""add annotation set link to map layer

Revision ID: 9165194191ce
Revises: 2d3e4f5a6b7c
Create Date: 2026-03-19 18:16:35.484825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9165194191ce'
down_revision: Union[str, None] = '2d3e4f5a6b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('idx_activity_logs_entity'), table_name='activity_logs')
    op.drop_index(op.f('idx_activity_logs_user'), table_name='activity_logs')
    op.drop_index(op.f('idx_annotations_class'), table_name='annotations')
    op.drop_index(op.f('idx_annotations_confidence'), table_name='annotations', postgresql_where='(confidence IS NOT NULL)')
    op.drop_index(op.f('idx_annotations_set'), table_name='annotations')
    op.alter_column('dataset_items', 'geometry',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='GeoJSON geometry of the item footprint',
               existing_nullable=True)
    op.drop_index(op.f('idx_datasets_stac_collection'), table_name='datasets')
    op.drop_index(op.f('idx_datasets_status'), table_name='datasets')
    op.drop_index(op.f('idx_datasets_temporal_extent'), table_name='datasets', postgresql_using='gist')
    op.drop_index(op.f('idx_job_outputs_job'), table_name='job_outputs')
    op.drop_index(op.f('idx_job_outputs_type_id'), table_name='job_outputs')
    op.add_column('map_layers', sa.Column('annotation_set_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'map_layers', 'annotation_sets', ['annotation_set_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_maps_created_by'), table_name='maps')
    op.alter_column('organization_members', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_organizations_clerk_org_id'), 'organizations', type_='unique')
    op.drop_constraint(op.f('uq_organizations_slug'), 'organizations', type_='unique')
    op.drop_index(op.f('ix_organizations_clerk_org_id'), table_name='organizations')
    op.create_index(op.f('ix_organizations_clerk_org_id'), 'organizations', ['clerk_org_id'], unique=True)
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.drop_index(op.f('idx_projects_created_by'), table_name='projects')
    op.drop_index(op.f('idx_styles_type'), table_name='styles')
    op.drop_constraint(op.f('uq_users_clerk_id'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_clerk_id'), table_name='users')
    op.create_index(op.f('ix_users_clerk_id'), 'users', ['clerk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_clerk_id'), table_name='users')
    op.create_index(op.f('ix_users_clerk_id'), 'users', ['clerk_id'], unique=False)
    op.create_unique_constraint(op.f('uq_users_clerk_id'), 'users', ['clerk_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_styles_type'), 'styles', ['type'], unique=False)
    op.create_index(op.f('idx_projects_created_by'), 'projects', ['created_by'], unique=False)
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=False)
    op.drop_index(op.f('ix_organizations_clerk_org_id'), table_name='organizations')
    op.create_index(op.f('ix_organizations_clerk_org_id'), 'organizations', ['clerk_org_id'], unique=False)
    op.create_unique_constraint(op.f('uq_organizations_slug'), 'organizations', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_organizations_clerk_org_id'), 'organizations', ['clerk_org_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('organization_members', 'role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_index(op.f('idx_maps_created_by'), 'maps', ['created_by'], unique=False)
    op.drop_constraint(None, 'map_layers', type_='foreignkey')
    op.drop_column('map_layers', 'annotation_set_id')
    op.create_index(op.f('idx_job_outputs_type_id'), 'job_outputs', ['output_type', 'output_id'], unique=False)
    op.create_index(op.f('idx_job_outputs_job'), 'job_outputs', ['job_id'], unique=False)
    op.create_index(op.f('idx_datasets_temporal_extent'), 'datasets', ['temporal_extent'], unique=False, postgresql_using='gist')
    op.create_index(op.f('idx_datasets_status'), 'datasets', ['status'], unique=False)
    op.create_index(op.f('idx_datasets_stac_collection'), 'datasets', ['stac_collection_id'], unique=False)
    op.alter_column('dataset_items', 'geometry',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='GeoJSON geometry of the item footprint',
               existing_nullable=True)
    op.create_index(op.f('idx_annotations_set'), 'annotations', ['annotation_set_id'], unique=False)
    op.create_index(op.f('idx_annotations_confidence'), 'annotations', ['confidence'], unique=False, postgresql_where='(confidence IS NOT NULL)')
    op.create_index(op.f('idx_annotations_class'), 'annotations', ['class_id'], unique=False)
    op.create_index(op.f('idx_activity_logs_user'), 'activity_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_activity_logs_entity'), 'activity_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('idx_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###
